#!/usr/bin/env python

import sys, os, stat, re

def printusage():
	print """
Syntax:  import-mh-folder directory [sqmail_command]

import-mh-folder reads a directory, and runs "SQmaiL fetch file" on
all the files in that folder with numerical filenames.  For instance, if

$ ls foo
1   12  15  18  20  23  26  29  31  34  37  4   42  45  7  comp409
10  13  16  19  21  24  27  3   32  35  38  40  43  5   8  profs
11  14  17  2   22  25  28  30  33  36  39  41  44  6   9  tech

Then running "import-mh-folder foo" would result in SQmaiL getting run
like so:

SQmaiL fetch file foo/1
SQmaiL fetch file foo/2
...
SQmaiL fetch file foo/45


If SQmaiL is not in your path or is not named "SQmaiL", you can run
import-mh-folder with a second argument that specifies the SQmaiL
path.  So "import-mh-folder foo /path/to/SQmaiL" would result in

/path/to/SQmaiL fetch file foo/1
etc.
"""

def printusageandexit():
	printusage()
	sys.exit(1)

def check_args():
	"""Make sure argument is right, return directory name"""
	global sqmail_cmd

	if len(sys.argv) < 2 or len(sys.argv) > 3:
		print "Error: Wrong number of arguments."
		printusageandexit()
	elif len(sys.argv) == 2: sqmail_cmd = "SQmaiL"
	else: sqmail_cmd = sys.argv[2]

	dirname = sys.argv[1]
	try: dirstats = os.stat(dirname)
	except os.error:
		print "Error: cannot find file %s" % dirname
		printusageandexit()

	if not stat.S_ISDIR(dirstats[stat.ST_MODE]):
		print "Error: file %s is not a directory" % dirname
		printusageandexit()
	return dirname

def get_sorted_list(dirname):
	"""Return sorted list of files to import"""
	filelist = os.listdir(dirname)
	regexp = re.compile("^[0-9]+$")

	numbers_only = filter(regexp.search, filelist)
	sortable_pairs = map(lambda x: (int(x), x), numbers_only)
	sortable_pairs.sort()
	return map(lambda pair, dirname = dirname: os.path.join(dirname, pair[1]),
			   sortable_pairs)

def sqmail_import(filename):
	"""Run sqmail fetch on filename"""
	cmdline = "%s fetch file %s" % (sqmail_cmd, filename)
	print cmdline
	if os.system(cmdline):
		print "External error attempting to run SQmaiL"
		sys.exit(2)


map(sqmail_import, get_sorted_list(check_args()))

