#!/usr/bin/env python
# SQmaiL execution stub
# $Source: /cvsroot/sqmail/sqmail/src/SQmaiL,v $
# $State: Exp $

import sys
# Note that the other sqmail modules are only imported when needed, to prevent
# Gnome from stealing the command line options when we don't want it.

def usage():
	print "Syntax: SQmaiL <command> [options]"
	print "Available commands:"
	print "  create-database    Create a new SQmaiL database"
	print "  gui                Start up the Gnome MUA"
	print "  scan               List the contents of a vfolder"
	print "  show               Show an individual message"
	print "For more help on individual commands, try the -h option for the"
	print "command in question."

if (len(sys.argv) < 1):
	usage()
	sys.exit(2)

cmd = sys.argv[1]
if (cmd == "gui"):
	import sqmail.gui.reader
	sqmail.gui.reader.SQmaiLReader()
elif (cmd == "scan"):
	import sqmail.cli.scan
	sqmail.cli.scan.SQmaiLScan()
elif (cmd == "show"):
	import sqmail.cli.show
	sqmail.cli.show.SQmaiLShow()
elif (cmd == "create-database"):
	import sqmail.cli.createdb
	sqmail.cli.createdb.SQmaiLCreateDB()
else:
	usage()
	sys.exit(2)

# Revision History
# $Log: SQmaiL,v $
# Revision 1.4  2001/01/09 11:41:24  dtrg
# Added the create-database CLI command.
#
# Revision 1.3  2001/01/08 15:34:28  dtrg
# Added the show CLI command.
#
# Revision 1.2  2001/01/08 14:58:54  dtrg
# Added the scan CLI command.
#
# Revision 1.1  2001/01/05 17:27:48  dtrg
# Initial version.

