#!/usr/bin/env python
# SQmaiL execution stub
# $Source: /cvsroot/sqmail/sqmail/src/SQmaiL,v $
# $State: Exp $

import sys
import os
# Note that the other sqmail modules are only imported when needed, to prevent
# Gnome from stealing the command line options when we don't want it.

# Check to see if we've been loaded with SQMAIL_LIBDIR set. If so, set us up
# to read modules and images from there.

if os.environ.has_key("SQMAIL_LIBDIR"):
	libdir = os.environ["SQMAIL_LIBDIR"]
	sys.path[0] = libdir

def usage():
	print "Syntax: SQmaiL <command> [options]"
	print "Available commands:"
	print "  create-database    Create a new SQmaiL database"
	print "  upgrade            Upgrade data from an old SQmaiL version"
	print "  recover            Attempt to recover broken data"
	print "  settings           Manage the SQmaiL configuration information"
	print "  purges             Manage the message purging facility"
	print "  gui                Start up the Gnome MUA"
	print "  vfolders           Manage vfolders"
	print "  scan               List the contents of a vfolder"
	print "  show               Show an individual message"
	print "For more help on individual commands, try the -h option for the"
	print "command in question."

if (len(sys.argv) < 2):
	usage()
	sys.exit(2)

cmd = sys.argv[1]
if (cmd == "gui"):
	import sqmail.gui.reader
	sqmail.gui.reader.SQmaiLReader()
elif (cmd == "scan"):
	import sqmail.cli.scan
	sqmail.cli.scan.SQmaiLScan()
elif (cmd == "show"):
	import sqmail.cli.show
	sqmail.cli.show.SQmaiLShow()
elif (cmd == "vfolders"):
	import sqmail.cli.vfolders
	sqmail.cli.vfolders.SQmaiLVFolders()
elif (cmd == "create-database"):
	import sqmail.cli.createdb
	sqmail.cli.createdb.SQmaiLCreateDB()
elif (cmd == "settings"):
	import sqmail.cli.settings
	sqmail.cli.settings.SQmaiLSettings()
elif (cmd == "purges"):
	import sqmail.cli.purges
	sqmail.cli.purges.SQmaiLPurges()
elif (cmd == "recover"):
	import sqmail.cli.recover
	sqmail.cli.recover.SQmaiLRecover()
elif (cmd == "upgrade"):
	import sqmail.cli.upgrade
	sqmail.cli.upgrade.SQmaiLUpgrade()
else:
	usage()
	sys.exit(2)

# Revision History
# $Log: SQmaiL,v $
# Revision 1.10  2001/05/23 10:21:31  dtrg
# Removed some debug tracing.
#
# Revision 1.9  2001/05/01 18:23:42  dtrg
# Added the Debian package building stuff. Now much easier to install.
# Some GUI tidying prior to the release.
# Did some work on the message DnD... turns out to be rather harder than I
# thought, as you can't have a CTree do its own native DnD and also drag
# your own stuff onto it at the same time.
#
# Revision 1.8  2001/02/23 19:50:26  dtrg
# Lots of changes: added the beginnings of the purges system, CLI utility
# for same, GUI utility & UI for same, plus a CLI vfolder lister.
#
# Revision 1.7  2001/02/20 18:14:05  dtrg
# Added the settings command. This gives you a basic CLI to the settings
# database, which should let you play with the configuration without having
# to start the GUI.
#
# Revision 1.6  2001/01/19 20:34:55  dtrg
# Added the recover and upgrade commands, plus the back-end code. recover
# will let you rebuild various bits of the database (currently just the
# vfolderlist). upgrade upgrades one version of the database to another.
#
# Revision 1.5  2001/01/10 12:17:16  dtrg
# Fixed an OB1 error when testing for a command; now, doing SQmaiL by itself
# no longer causes an ugly traceback.
#
# Revision 1.4  2001/01/09 11:41:24  dtrg
# Added the create-database CLI command.
#
# Revision 1.3  2001/01/08 15:34:28  dtrg
# Added the show CLI command.
#
# Revision 1.2  2001/01/08 14:58:54  dtrg
# Added the scan CLI command.
#
# Revision 1.1  2001/01/05 17:27:48  dtrg
# Initial version.

